### ISSUE TITLE
Handling errors in backend and package conflict in requirements

### ISSUE THREAD

**Issue by okaditya84** [akashgreninja/Doggonation#10]
There are no error handling statements in every python file in the backend folder.
As well as there may be conflicts in installing requirements.txt with some packages as pip will be looped in ambiguity of versions.

I can handle this task with my expertise in flask/django.

**Comment by akashgreninja** [comment]
Please review @2deadmen then assign

**Comment by okaditya84** [comment]
> Please review @2deadmen then assign 

Am I assigned this ?

**Comment by 2deadmen** [comment]
> > Please review @2deadmen then assign
> 
> Am I been assigned this issue ? If so kindly add a gssoc23 label to my assignment.

No , sorry for the confusion earlier ,we have decided not to give access to server side
