### ISSUE TITLE
Improve UI: Sign in Page

### ISSUE THREAD

**Issue by rishuraj1** [akashgreninja/Doggonation#11]
For a better user experience we must update the design and look of the sign in page.

![Screenshot (89)](https://github.com/akashgreninja/Doggonation/assets/47839626/aa2823db-ea33-4f03-9d39-b8a0bd16cd1f)

@akashgreninja   Could you assign me to this under GSSoC'23. I would really like to contribute to this wonderful project. Thank You!

**Comment by mvpfrever** [comment]
hello sir can you assign this task to me I can create it highly attractive it will be my pleasure if i work on it

**Comment by sujitmemane** [comment]
Hello, Sir! 👋🏼

I am [Sujit Memane](https://thesujitmemane.vercel.app/), a front-end React developer with expertise in creating visually stunning user interfaces. I have a strong portfolio that showcases my past work, highlighting my skills and abilities in designing attractive UIs.

I would be thrilled to contribute to the improvement of your Login Page. Please consider assigning this issue to me, as it would be my pleasure to work on it and bring my expertise to create a better user experience for your users. 😊🎨

Looking forward to the opportunity!

Porrtfolio Link : https://thesujitmemane.vercel.app/
Recent Project : https://bummer-eight.vercel.app/

**Comment by tusharv01** [comment]
Hi Sir I am a gssoc contributor and I have the ability to design this sign in ui, Please assign me this issue.    Provide you the PR within three days.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by akashgreninja** [comment]
It has been fixed but if you want we need an admin page we will be happy to pull PR's from there

**Comment by akashgreninja** [comment]
check issue #17
