### ISSUE TITLE
Creating Templates to add new feature and report bugs.

### ISSUE THREAD

**Issue by tuhinaww** [akashgreninja/Doggonation#13]
Hey, We can have GitHub template so that new contributors can open issue, suggest changes, report bugs in more descriptive way. It would be beneficial for mentors and well as the contributors.

If you want, I can work on this. Please assign this issue to me I am from GSSoC 2023.

Thank you.

**Comment by tuhinaww** [comment]
Please add GSSoC label to it as well :)

**Comment by akashgreninja** [comment]
Ill assign you this but ig i will have to add th e Gssoc label when we pull the  pr

**Comment by tuhinaww** [comment]
If there is anything you would like me to update you can always open it up again and pin me. I can update :)
