### ISSUE TITLE
Add ContributingGuidelines.md

### ISSUE THREAD

**Issue by shanvijha30** [akashgreninja/Doggonation#14]
The Contributing Guideline documentation will contain set of guidelines that will help contributors during the contribution process.
File type markdown.

**Comment by shanvijha30** [comment]
@akashgreninja could you please assign this issue to me.
Thank you!

**Comment by akashgreninja** [comment]
Done go ahead with the changes

**Comment by shanvijha30** [comment]
@akashgreninja Could you please add GSSOC 23 label to this issue.
Thank you!

**Comment by shanvijha30** [comment]
@akashgreninja Added PR [#24](https://github.com/akashgreninja/Doggonation/pull/24)
Please review it.

**Comment by akashgreninja** [comment]
Thank you @shanvijha30 I have merged it also have added the label if there is anything else I have to add let me know for now I'm closing this
