### ISSUE TITLE
[Feature]: What about a Landing Page 

### ISSUE THREAD

**Issue by Hemant2335** [akashgreninja/Doggonation#19]
<!--
Example how to mark a checkbox:-
- [x] My code follows the code style of this project.

- [x ] Would you like to take up this task? 
- [x ] Are you from GSSoC'23? 

|   ✨  |   What about a New Landing Page|

|-----|---------------------------------|

| My feature is , that right you don't have any landing page and for a person to get a overview of the Website 
 -> Also I am quite a familiar with designing the frontend part
| 

| Alternative Solution could be creating  a welcome page right there on the dashboard |

So please assign this task to me under GSSOC'23

Thankyou

**Comment by akashgreninja** [comment]
Yes please make it happen we will be happy to pull it

**Comment by Hemant2335** [comment]
Ok Thanks I am on it
