### ISSUE TITLE
[Feature]:  want to add dark mode  

### ISSUE THREAD

**Issue by poudelsaroj** [akashgreninja/Doggonation#23]
- [x ] Would you like to take up this task? 
- [x ] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | Kindly provide an explanation of the problem that your feature aims to resolve. |
| **Describe the solution you'd like** | Please present a concise and precise description of the solution you envision. |
| **Describe alternatives you've considered** | Elaborate on any alternative solutions or features that you have already evaluated as potential approaches. |
| **Additional context** | Include any supplementary information, contextual details, relevant screenshots, or supporting materials that can aid in better understanding and supporting your feature request. |

**Comment by akashgreninja** [comment]
Hey @poudelsaroj im assigning you this issue get it done

**Comment by poudelsaroj** [comment]
ok assign me in @akashgreninja

**Comment by shubham725809** [comment]
I am good at web development and have developed many web development projects, so adding this feature is not a big task for me. so please assign me this and I am also a GSSOC 2023 contributor.

**Comment by 2003souvik** [comment]
please assign me this

**Comment by akashgreninja** [comment]
hey @poudelsaroj any updates ?

**Comment by poudelsaroj** [comment]
@akashgreninja  i am working on it. will finish till monday .

**Comment by EffDuBois** [comment]
@poudelsaroj hey, a small change, try to adhere to the yellow colour theme provided in the "contributing " file if possible

**Comment by poudelsaroj** [comment]
@EffDuBois ok will do this @akashgreninja  firstly please assign me looks like i haven't been assigned in this.

**Comment by EffDuBois** [comment]
@poudelsaroj any updates?

**Comment by VishalVinayRam** [comment]
please assign me  will do it now

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign
