### ISSUE TITLE
[Feature]: Workflow for closing old issues 

### ISSUE THREAD

**Issue by Tushar98644** [akashgreninja/Doggonation#27]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | I would like to add a workflow action for closing inactive old issues |
| **Describe the solution you'd like** | Please present a concise and precise description of the solution you envision. |

**Comment by Tushar98644** [comment]
@akashgreninja I would like to take up the issue

**Comment by akashgreninja** [comment]
Assigned to @Tushar98644
