### ISSUE TITLE
[BUG]: Follow and following routes come under post request not get update this 

### ISSUE THREAD

**Issue by akashgreninja** [akashgreninja/Doggonation#36]
- [ ] Would you like to take up this task? 
- [ ] Are you from GSSoC'23? 

---

|  🐞   |   Bug report                         |
|-----|--------------------------------------|
| **Describe the bug** | Please provide a clear and concise description of the issue encountered |
| **Location of the bug** | If known, please specify the file location where the bug was identified |
| **Expected behavior** | What should happen instead of the observed bug? |

## Screenshots (if any)
---
|     Screenshot 1 (if any)       |       Screenshot 2 (if any)     |
| :-----------------: | :------------------: |
| ![Screenshot 1](link) | ![Screenshot 2](link) |

Please provide any necessary screenshots to illustrate.

**Comment by 2deadmen** [comment]
bug fixed
