### ISSUE TITLE
Adding badges to README.md File

### ISSUE THREAD

**Issue by AmanSingh6574** [akashgreninja/Doggonation#38]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|

|**Additional context** |![image](https://github.com/akashgreninja/Doggonation/assets/113782984/f4dde34a-bade-420b-88ea-aed7bca89487) 

pls assign me this issue under GSSOC'23 label @akashgreninja

**Comment by akashgreninja** [comment]
Go ahead @AmanSingh6574

**Comment by AmanSingh6574** [comment]
@EffDuBois pls add level to issue
