### ISSUE TITLE
[Feature]: add code of conduct 

### ISSUE THREAD

**Issue by S-ishita** [akashgreninja/Doggonation#43]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** 
Hi there!
I recommend adding a CODE_OF_CONDUCT.md file to your repository. This file would serve as a guide for potential contributors, providing them with a clear set of expectations, guidelines, and behavior standards for participating in your project. It plays an essential role in creating a welcoming and inclusive environment for everyone involved.

Thank you!
| **Describe the solution you'd like**

I would like to work on this issue. Please assign it to me under GSSoC'23.

**Comment by akashgreninja** [comment]
Go ahead @S-ishita
