### ISSUE TITLE
[Feature]: Improve Frontend

### ISSUE THREAD

**Issue by ritika1408** [akashgreninja/Doggonation#45]
- [ ] Would you like to take up this task? 
- [ ] Are you from GSSoC'23? Yes.

I would like to improve the frontend of the project. Please assign me the issue..

**Comment by akashgreninja** [comment]
@ritika1408 feel free to do the major changes without the backend it'll still render but you might have to put sample data and check will that be ok?

**Comment by EffDuBois** [comment]
@ritika1408 Please give a list of what changes you propose to make, and try to propose major changes in separate issues.

**Comment by oshinsaraf** [comment]
Can you assign this to me under GSSOC'23?
