### ISSUE TITLE
[Feature]: Dockerize the application

### ISSUE THREAD

**Issue by Codeansh** [akashgreninja/Doggonation#46]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | I want to make the application more scalable and make sure of flexible resource sharing. |
| **Describe the solution you'd like** | To make the application more scalable I want to dockerize the application |
| **Describe alternatives you've considered** | Another solution for scalability in my opinion might be deploying the application on some cloud platform like AWS, but containerization will still help in that case. |
| **Additional context** | https://www.knowledgehut.com/blog/devops/why-use-docker |

**Comment by Codeansh** [comment]
Please assign me this issue.

**Comment by EffDuBois** [comment]
Containerization will be handled by us, thank you.
