### ISSUE TITLE
[Feature]: Improvise the database interaction with help of an ORM rather then direct SQL query

### ISSUE THREAD

**Issue by bshantherishenoy** [akashgreninja/Doggonation#47]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | Current code involves in lot of SQL query written  |
| **Describe the solution you'd like** | Can update with the help of an ORM (object relation mapper) |

**Comment by akashgreninja** [comment]
While I acknowledge the advantages of using an ORM (Object-Relational Mapping) for simplified database interactions, I believe that, in our case, working directly with MySQL without an ORM would be more beneficial. Direct SQL queries provide us with greater control and flexibility over our database operations, allowing us to fine-tune and optimize queries to meet our specific requirements. Moreover, this approach enables us to enhance our SQL query writing skills and gain a deeper understanding of the database system. By opting for direct MySQL interaction, we can optimize our queries for improved performance and develop a stronger command over the database

Im closing this but thank you for the advise if you have any other contributions feel free to raise an issue
