### ISSUE TITLE
[UI Fix]:  Improve the Sidebar/Navbar

### ISSUE THREAD

**Issue by EffDuBois** [akashgreninja/Doggonation#50]
|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | The navbar has a bad ui and layout |
| **Describe the solution you'd like** |<ul><li>**IMPROVE THE SIDEBAR/NAVBAR UI**</li><li> put search on left which opens a search bar </li><li> Divide the whole sidebar into a single list instead of lists and sub lists with order - <ol><li>Home</li><li>Search</li><li>Chat</li><li>Friends</li>-on the bottom<li>About us(instead of donation)</li><li>logout</li></ol><li>add appropriate icons(using fa-icons preferably) to add icons to missing or newly added fields</li><li>Left align all the list items</li><ul> |
| **Additional context** | This is done to make the ui less cluttered and more streamlined towards the content |

edit: updated the guidellines

**Comment by kash5811** [comment]
please assign this task to me under Gssoc'23

**Comment by EffDuBois** [comment]
@kash5811 I'll assign it to you, see the updated guidelines

**Comment by EffDuBois** [comment]
@kash5811 see the guidelines please

**Comment by kash5811** [comment]
Okay

**Comment by EffDuBois** [comment]
you can use the style of the post section

**Comment by kash5811** [comment]
okay noted.

**Comment by kash5811** [comment]
is it compulsory to use tailwind?

**Comment by EffDuBois** [comment]
@kash5811 hey, yes try to use tailwind or material UI as much as possible. if it's not implementable by tailwind then you can use plain css. 
If you're having difficulty figuring out tailwind classes use can use this [Documentation ](https://tailwindcss.com/docs/installation)

**Comment by kash5811** [comment]
can I reshape the whole sidebar
