### ISSUE TITLE
[BUG]: Donation page carousel and sidebar

### ISSUE THREAD

**Issue by EffDuBois** [akashgreninja/Doggonation#54]
|  🐞   |   Bug report                         |
|-----|--------------------------------------|
| **Describe the bug** | <li>The carousel does not render<li>Sidebar renders if donation page is opened through the sidebar |
| **Location of the bug** | Landingpage element|
| **Expected behavior** | <li>Carousel should render, <li>sidebar should be completely disabled <li>A back/ home button should be added <li> the element should be renamed appropriately  |

## Screenshots (if any)
---
|    Screenshot 1  |       Screenshot 2    |
| :-----------------: | :------------------: |
| ![image](https://github.com/akashgreninja/Doggonation/assets/46263523/e5dd392f-d282-4c74-8329-c0f4c2f84c56) | ![image](https://github.com/akashgreninja/Doggonation/assets/46263523/48ac7c0e-b70b-4a85-a770-82fa02a74878) |

**Comment by EffDuBois** [comment]
@Hemant2335 can you fix this

**Comment by Hemant2335** [comment]
Yaa I can  do that please assign it to me 

Thank you

**Comment by Hemant2335** [comment]
Ohh okay now I understand last time you want me to put the entire same page as the donation page ,
and I thought you only wanted the about section ,

Okay now I fix that
