### ISSUE TITLE
[UI Fix]:  SignIn page

### ISSUE THREAD

**Issue by EffDuBois** [akashgreninja/Doggonation#55]
|   ✨  |    request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | Signin Page UI Fix|
| **Describe the solution you'd like** | <li>**IMPROVE SINGIN PAGE UI - adehere to the style of the explore page, more specifically the post section <li>Make the singin div into a modal style/floating window <li> move the div to left <li> change background image acoordingly|
| **Additional context** | This is towards trying to unify the style of the website|

**Comment by itsPriyanshuhere** [comment]
Can this problem be assigned to me with the gssoc'23 label? I would aim to create an inquisitive design to go with the rest of the website's elements.

**Comment by EffDuBois** [comment]
@itsPriyanshuhere i'll assign it to you

**Comment by oshinsaraf** [comment]
Can you assign this to me under GSSOC'23?
