### ISSUE TITLE
[Logo]:doggonation logo + appwrite logo

### ISSUE THREAD

**Issue by akashgreninja** [akashgreninja/Doggonation#59]
- [ ] Would you like to take up this task? 
- [ ] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
Need a appwrite logo next to the doggonation logo on the appwrite branch 
it should say 
"Doggonation Powered by appwrite"

**Comment by mahak-dev** [comment]
I can do this task under the GSSOC'2023

**Comment by akashgreninja** [comment]
@mahak-dev go ahead'
