### ISSUE TITLE
Addition in Issue Template

### ISSUE THREAD

**Issue by Anshika-Jain02** [akashgreninja/Doggonation#62]
## Description:

Hi there!

*I noticed that the repository does not have an appropriate issue template.*

*Issue Template: I want to add  some more points to your issue template like styling changes, documentation, etc*

Please assign this issue to me under Gssoc'23 @akashgreninja

**Comment by akashgreninja** [comment]
@Anshika-Jain02 
 Thank you for the proposal but we are actually not taking any readme or the project utility  issues as  our 90% issues have filled with them but if its related to the base code feel free to open an issue
