### ISSUE TITLE
[Feature]: ADDING A FEEDBACK SECTION

### ISSUE THREAD

**Issue by kharshita590** [akashgreninja/Doggonation#66]
- [Y ] Would you like to take up this task? 
- [ Y] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | Kindly provide an explanation of the problem that your feature aims to resolve. |
| **Describe the solution you'd like** | Please present a concise and precise description of the solution you envision. |
| **Describe alternatives you've considered** | Elaborate on any alternative solutions or features that you have already evaluated as potential approaches. |
| **Additional context** | Include any supplementary information, contextual details, relevant screenshots, or supporting materials that can aid in better understanding and supporting your feature request. |

**Comment by AkankshaNarula** [comment]
Heyy  could you guide what do you expect me to do in this and what all tech stacks I require for it in a little detail. Actually,I am a student currently in first year and thereby a complete novice to open source, hence your guidance will be highly appreciated. :)
