### ISSUE TITLE
[Feature]: Scroll to top button

### ISSUE THREAD

**Issue by kaashikaagrawal** [akashgreninja/Doggonation#67]
- [x] Would you like to take up this task? 
- [x ] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | Once the user has scrolled through the webpage, there is no button available to scroll back to the top with one click. |
| **Describe the solution you'd like** | I can provide a scroll to the top button that appears as the user begins scrolling near the scroll bar. |

**Comment by akashgreninja** [comment]
@kaashikaagrawal have it done

**Comment by kaashikaagrawal** [comment]
while running npm install, there are many dependency errors due to the packages listed in package.json being deprecated. The app is not rendering properly on the screen. What can I do?

**Comment by akashgreninja** [comment]
npm i -f works
