### ISSUE TITLE
Additions in Issue template

### ISSUE THREAD

**Issue by Anshika-Jain02** [akashgreninja/Doggonation#69]
## Description:

*I noticed that the repository does not have an appropriate issue template.*

*Issue Template: I want to add  some more points to your issue template like styling changes, documentation, etc*

Please assign this issue to me under Gssoc'23 @akashgreninja

**Comment by akashgreninja** [comment]
Thank you for expressing your interest in contributing to our project and participating in Gssoc'23. We value your enthusiasm and eagerness to contribute.

However, at this time, we would like to keep the issue template, readme, and other non-core project areas unchanged. These aspects have been carefully crafted and aligned with our project's guidelines and requirements.

That being said, we are delighted to have you contribute to the core functionality of our project. There are several key areas that require attention and enhancement. We believe your skills and expertise would be a valuable addition in these areas. If you are interested, we can provide you with more detailed information about the specific features and functionality that need improvement.

We appreciate your understanding regarding our decision to maintain the existing documentation and non-core aspects of the project. We genuinely look forward to collaborating with you on the core functionality, where your contributions can make a significant impact.

Please let us know if you are still interested, and we will provide you with further guidance and support to get you started.
