### ISSUE TITLE
[Feature]: Add the black linter workflow 

### ISSUE THREAD

**Issue by metabiswadeep** [akashgreninja/Doggonation#70]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using the prettier linter in GitHub actions. |
| **Describe the solution you'd like** | Add the black linter workflow to ensure proper and uniform linting of the codebase|

**Comment by akashgreninja** [comment]
Thank you for expressing your interest in contributing to our project and participating in Gssoc'23. We value your enthusiasm and eagerness to contribute.

However, at this time, we would like to keep the issue template, readme, and other non-core project areas unchanged. These aspects have been carefully crafted and aligned with our project's guidelines and requirements.

That being said, we are delighted to have you contribute to the core functionality of our project. There are several key areas that require attention and enhancement. We believe your skills and expertise would be a valuable addition in these areas. If you are interested, we can provide you with more detailed information about the specific features and functionality that need improvement.

We appreciate your understanding regarding our decision to maintain the existing documentation and non-core aspects of the project. We genuinely look forward to collaborating with you on the core functionality, where your contributions can make a significant impact.

Please let us know if you are still interested, and we will provide you with further guidance and support to get you started.

**Comment by metabiswadeep** [comment]
> Thank you for expressing your interest in contributing to our project and participating in Gssoc'23. We value your enthusiasm and eagerness to contribute.
> 
> However, at this time, we would like to keep the issue template, readme, and other non-core project areas unchanged. These aspects have been carefully crafted and aligned with our project's guidelines and requirements.
> 
> That being said, we are delighted to have you contribute to the core functionality of our project. There are several key areas that require attention and enhancement. We believe your skills and expertise would be a valuable addition in these areas. If you are interested, we can provide you with more detailed information about the specific features and functionality that need improvement.
> 
> We appreciate your understanding regarding our decision to maintain the existing documentation and non-core aspects of the project. We genuinely look forward to collaborating with you on the core functionality, where your contributions can make a significant impact.
> 
> Please let us know if you are still interested, and we will provide you with further guidance and support to get you started.
> 
> 

I am very much interested and would love to get guidance and support from you. Please do let me know more about where I can contribute.
