### ISSUE TITLE
Make a attractive UI of search bar 

### ISSUE THREAD

**Issue by Nikita110602** [akashgreninja/Doggonation#72]
![Screenshot (64)](https://github.com/akashgreninja/Doggonation/assets/111515819/97da2301-e484-47ff-b881-8ab933051848)

**Comment by Nikita110602** [comment]
pls assign me this work

**Comment by akashgreninja** [comment]
hey @Nikita110602 i think you have gotten it confused 
that was the blog in which we wrote about our website our website is not live still 
so that is the hashnode searchbar

**Comment by akashgreninja** [comment]
Close this issue if there is nothing else but 
you could still refer the reader and try to make this run on codepaces or locally
