### ISSUE TITLE
[Feature]:  Add Captcha verification to the register form

### ISSUE THREAD

**Issue by Manice18** [akashgreninja/Doggonation#74]
- [x] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | A captcha verification must be present to differentiate between a human and a bot |
| **Describe the solution you'd like** | Will like to add a captcha verification below the register form before submitting |

**Comment by akashgreninja** [comment]
Get it done !!

**Comment by Manice18** [comment]
Yup. Will get back soon.

**Comment by Manice18** [comment]
![image](https://github.com/akashgreninja/Doggonation/assets/91601706/8883c28b-114b-4792-a48e-45b5662c211e)

In the frontend codebase i dont see vite anywhere

**Comment by akashgreninja** [comment]
We went back to CRA we have to remove it  will do that now
