### ISSUE TITLE
[Feature]: Add site link in readme file

### ISSUE THREAD

**Issue by ShikhaaT44** [akashgreninja/Doggonation#82]
- [ ] Would you like to take up this task? 
- [x] Are you from GSSoC'23? 

|   ✨  |   Feature request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | This might be a problem as the users will try to review the website first before deciding to contribute or make changes. Also getting a preview of the website helps contributors to have a quick glance on the updates of the website. |
| **Describe the solution you'd like** | Please add a website link in the readme file where this website is hosted currently |
| **Describe alternatives you've considered** | NA |
| **Additional context** | Even though the site is under progress, temporarily provide any netlify link  if possible. |

**Comment by akashgreninja** [comment]
We want no more changes to the readme file at the moment  feel free to raise requests related to the main project
